seed: 42

model:
  name: yolov1_resnet50
  pretrained_backbone: true
  pretrained_checkpoint: ""
  strict_load: true

data:
  root_dir: /content/voc_repo/VOC_Detection
  train_split: train
  val_split: test
  image_size: 448
  grid_size: 7
  boxes_per_cell: 2
  num_classes: 20
  batch_size: 8
  num_workers: 2
  pin_memory: false
  normalize_mean: null
  normalize_std: null

loss:
  lambda_coord: 5.0
  lambda_noobj: 0.5

train:
  epochs: 20
  optimizer: adamw
  lr: 1.0e-4
  momentum: 0.9
  weight_decay: 1.0e-4
  warmup_start_factor: 0.1
  warmup_frac: 0.05
  decay1_frac: 0.70
  decay2_frac: 0.90
  gamma1: 0.1
  gamma2: 0.01
  device: cuda
  mixed_precision: true
  log_interval: 100
  output_dir: /content/YOLO2D-t/outputs/yolov1_voc_resnet50

eval:
  conf_threshold: 0.05
  nms_iou: 0.5
  eval_iou: 0.5
